# ing1 Ünite 1: u1k2 (Kişilik) ve u1k3 (Karşılaştırma) konu dosyalarını üretir.
# Çalıştır: python3 gen_ing1_u1.py  → public/ing1/konular/u1k2.json, u1k3.json
import json

BG = "<rect width='120' height='120' rx='22' fill='#1b2340'/>"
SKIN, INK = "#ffd6a5", "#1b2340"


def svg(*parca):
    return "<svg viewBox='0 0 120 120' xmlns='http://www.w3.org/2000/svg' role='img'>" + BG + "".join(parca) + "</svg>"


def yuz(cx, cy, r, agiz="gul", goz="acik"):
    """Basit yüz: daire + iki göz + ağız. agiz: gul / duz / asik; goz: acik / kapali."""
    ex, ey = r * 0.35, r * 0.1
    s = f"<circle cx='{cx}' cy='{cy}' r='{r}' fill='{SKIN}'/>"
    gr = max(1.2, r * 0.12)
    if goz == "kapali":
        for x in (cx - ex, cx + ex):
            s += f"<path d='M{x - gr * 1.6:.1f} {cy - ey:.1f} q{gr * 1.6:.1f} {gr * 1.4:.1f} {gr * 3.2:.1f} 0' stroke='{INK}' stroke-width='2' fill='none' stroke-linecap='round'/>"
    else:
        for x in (cx - ex, cx + ex):
            s += f"<circle cx='{x:.1f}' cy='{cy - ey:.1f}' r='{gr:.1f}' fill='{INK}'/>"
    ay = cy + r * 0.35
    if agiz == "gul":
        s += f"<path d='M{cx - ex:.1f} {ay:.1f} q{ex:.1f} {r * 0.3:.1f} {2 * ex:.1f} 0' stroke='{INK}' stroke-width='2' fill='none' stroke-linecap='round'/>"
    elif agiz == "asik":
        s += f"<path d='M{cx - ex:.1f} {ay + r * 0.12:.1f} q{ex:.1f} {-r * 0.3:.1f} {2 * ex:.1f} 0' stroke='{INK}' stroke-width='2' fill='none' stroke-linecap='round'/>"
    else:
        s += f"<path d='M{cx - ex * 0.8:.1f} {ay:.1f}h{ex * 1.6:.1f}' stroke='{INK}' stroke-width='2' stroke-linecap='round'/>"
    return s


def kisi(cx, taban, boy, renk, r=10, agiz="gul", en=18):
    """Ayakta duran kişi: gövde (yuvarlak dikdörtgen) + baş. boy = gövde yüksekliği."""
    ust = taban - boy
    return (f"<rect x='{cx - en / 2}' y='{ust}' width='{en}' height='{boy}' rx='7' fill='{renk}'/>"
            + yuz(cx, ust - r + 1, r, agiz))


def kutu(x, y, w, h, renk, serit="#f5f6fa"):
    return (f"<rect x='{x}' y='{y}' width='{w}' height='{h}' rx='3' fill='{renk}'/>"
            f"<path d='M{x + w / 2} {y}v{h}M{x} {y + h / 2}h{w}' stroke='{serit}' stroke-width='3'/>")


ZEMIN = "<path d='M18 104h84' stroke='#5a6280' stroke-width='3' stroke-linecap='round'/>"

# ---------------------------------------------------------------- u1k2 Kişilik
k2_svg = {
    "honest": svg(
        yuz(44, 66, 22),
        "<path d='M66 20h40q6 0 6 6v22q0 6-6 6H82l-8 8v-8h-8q-6 0-6-6V26q0-6 6-6z' fill='#f5f6fa'/>",
        "<path d='M74 37l7 7 14-14' stroke='#3cc47c' stroke-width='5' fill='none' stroke-linecap='round' stroke-linejoin='round'/>",
        "<path d='M30 98q14-10 28 0' fill='#3cc47c'/>"),
    "generous": svg(
        kisi(34, 104, 36, "#4ea8de"), kisi(88, 104, 36, "#ff7a33"),
        "<path d='M44 76h14M74 76h4' stroke='#ffd6a5' stroke-width='6' stroke-linecap='round'/>",
        kutu(52, 60, 22, 20, "#ff5a8a"),
        "<path d='M58 60q5-10 5 0q0-10 5 0' stroke='#f2c14e' stroke-width='3' fill='none'/>",
        "<path d='M63 30c-4-4-9 1-5 5l5 4 5-4c4-4-1-9-5-5z' fill='#ff5a6e'/>"),
    "punctual": svg(
        "<circle cx='60' cy='58' r='34' fill='#f5f6fa'/><circle cx='60' cy='58' r='34' stroke='#f2c14e' stroke-width='6' fill='none'/>",
        "".join(f"<circle cx='{60 + 26 * x}' cy='{58 + 26 * y}' r='2.5' fill='{INK}'/>" for x, y in ((0, -1), (1, 0), (0, 1), (-1, 0))),
        "<path d='M60 58V36M60 58h14' stroke='#1b2340' stroke-width='5' stroke-linecap='round'/><circle cx='60' cy='58' r='4' fill='#ff5a6e'/>",
        "<circle cx='92' cy='92' r='15' fill='#3cc47c'/><path d='M85 92l5 5 9-10' stroke='#f5f6fa' stroke-width='4' fill='none' stroke-linecap='round' stroke-linejoin='round'/>"),
    "outgoing": svg(
        ZEMIN, kisi(30, 104, 30, "#4ea8de", 9), kisi(90, 104, 30, "#ff7a33", 9), kisi(60, 104, 40, "#3cc47c", 11),
        "<path d='M70 66l14-20' stroke='#ffd6a5' stroke-width='6' stroke-linecap='round'/>",
        "<path d='M86 34q6 2 6 8M92 28q8 4 8 14' stroke='#f2c14e' stroke-width='3' fill='none' stroke-linecap='round'/>"),
    "easy-going": svg(
        "<path d='M14 92q46 26 92 0' stroke='#c58b5a' stroke-width='5' fill='none'/><path d='M14 92V30M106 92V30' stroke='#5a6280' stroke-width='4' stroke-linecap='round'/>",
        "<path d='M30 88q30 14 62 0l-4-14H34z' fill='#4ea8de'/>",
        yuz(42, 68, 14, "gul", "kapali"),
        "<path d='M84 34v18M84 34l10-3v18' stroke='#f2c14e' stroke-width='3' fill='none'/><circle cx='81' cy='52' r='4' fill='#f2c14e'/><circle cx='91' cy='49' r='4' fill='#f2c14e'/>"),
    "stubborn": svg(
        yuz(50, 58, 26, "duz"),
        "<path d='M32 40l12 5M68 40l-12 5' stroke='#1b2340' stroke-width='4' stroke-linecap='round'/>",
        "<path d='M26 92h48' stroke='#ffd6a5' stroke-width='10' stroke-linecap='round'/><path d='M30 98l40-12' stroke='#ff7a33' stroke-width='10' stroke-linecap='round'/>",
        "<rect x='88' y='30' width='18' height='60' rx='3' fill='#c58b5a'/><path d='M88 46h18M88 62h18M88 78h18M97 30v16M97 62v16' stroke='#7a4a2a' stroke-width='2'/>"),
    "selfish": svg(
        ZEMIN, "<rect x='28' y='52' width='26' height='52' rx='8' fill='#ff7a33'/>", yuz(41, 40, 12),
        kutu(26, 58, 20, 14, "#ff5a8a"), kutu(30, 72, 24, 16, "#4ea8de"), kutu(34, 88, 16, 12, "#f2c14e", INK),
        "<path d='M24 66q-6 16 6 26M58 66q6 16-6 26' stroke='#ffd6a5' stroke-width='6' fill='none' stroke-linecap='round'/>",
        kisi(88, 104, 30, "#5a6280", 10, "asik"),
        "<path d='M72 84h8M96 84h8' stroke='#ffd6a5' stroke-width='5' stroke-linecap='round'/>"),
}

u1k2 = {
    "id": "u1k2",
    "unite": "Unit 1: Appearance and Personality",
    "baslik": "Kişiliği Anlatma (Personality)",
    "sayfalar": "s. 10–26",
    "giris": "Bu konuda insanların kişiliğini, yani nasıl biri olduklarını anlatan İngilizce kelimeleri öğreneceğiz: dürüst mü, cömert mi, inatçı mı? İngilizce kelimelere dokunarak dinleyebilirsin. Bu konunun sorusu: {{What is she like?}} Yani: O nasıl biri?",
    "kavramlar": [
        {"ad": "honest", "renk": "#3cc47c", "svg": k2_svg["honest"],
         "aciklama": "Dürüst demektir. Dürüst kişi her zaman doğruyu söyler.",
         "ek": "Kitapta dürüst kişi için: {{She never tells lies.}} Hiç yalan söylemez. (s. 15)",
         "akilda": "dürüst",
         "ornek": "She's always honest, generous and fair.",
         "ornekTr": "O her zaman dürüst, cömert ve adildir. (s. 12)",
         "soru": {"soru": "{{She never tells lies.}} (Hiç yalan söylemez.) Bu kişi nasıl biri?",
                  "secenekler": ["honest", "stubborn", "selfish"], "dogru": 0,
                  "ipucu": "Bilgi kartına bak: her zaman doğruyu söyleyen kişi.",
                  "aciklama": "Yalan söylemeyen kişi {{honest}}: dürüsttür. (s. 15)"}},
        {"ad": "generous", "renk": "#ff5a8a", "svg": k2_svg["generous"],
         "aciklama": "Cömert demektir. Kitaptaki tanım: vermeye ve paylaşmaya istekli olan kişi.",
         "ek": "Kitaptaki İngilizce tanım: {{Willing to give and share.}} (s. 10)",
         "akilda": "cömert",
         "ornek": "Mark is a generous boy.",
         "ornekTr": "Mark cömert bir çocuktur. (s. 14)",
         "soru": {"soru": "{{She buys gifts for her friends.}} (Arkadaşlarına hediye alır.) Bu kişi nasıl biri?",
                  "secenekler": ["punctual", "generous", "stubborn"], "dogru": 1,
                  "ipucu": "Hediye almak, vermek ve paylaşmaktır. Kartta hangi kelime öyleydi?",
                  "aciklama": "Vermeyi ve paylaşmayı seven kişi {{generous}}: cömerttir. (s. 10, 15)"}},
        {"ad": "punctual", "renk": "#f2c14e", "svg": k2_svg["punctual"],
         "aciklama": "Dakik demektir. Dakik kişi her yere zamanında gelir, geç kalmaz.",
         "ek": "Kitaptaki tanım: {{Arriving or taking place at an arranged time.}} Kararlaştırılan saatte gelmek. (s. 10)",
         "akilda": "dakik, zamanında",
         "ornek": "She is punctual, honest and smart.",
         "ornekTr": "O dakik, dürüst ve akıllıdır. (s. 17)",
         "soru": {"soru": "{{She goes everywhere on time.}} (Her yere zamanında gider.) Bu kişi nasıl biri?",
                  "secenekler": ["outgoing", "selfish", "punctual"], "dogru": 2,
                  "ipucu": "Saat resmini hatırla: zamanında gelen kişi.",
                  "aciklama": "Her yere zamanında giden kişi {{punctual}}: dakiktir. (s. 10, 15)"}},
        {"ad": "outgoing", "renk": "#4ea8de", "svg": k2_svg["outgoing"],
         "aciklama": "Dışa dönük, sosyal demektir. Arkadaşlarıyla vakit geçirmeyi sever, çok arkadaşı olur.",
         "ek": "Kitapta Mike hep arkadaşlarıyla takılır: {{Mike always hangs out with his friends.}} (s. 13)",
         "akilda": "dışa dönük, sosyal",
         "ornek": "She isn't very outgoing, but she is very punctual.",
         "ornekTr": "Çok dışa dönük değildir ama çok dakiktir. (s. 14)",
         "soru": {"soru": "{{She has a lot of friends.}} (Çok arkadaşı var.) Bu kişi nasıl biri?",
                  "secenekler": ["outgoing", "honest", "punctual"], "dogru": 0,
                  "ipucu": "Resimde ortadaki çocuk arkadaşlarının arasında el sallıyor.",
                  "aciklama": "Çok arkadaşı olan, sosyal kişi {{outgoing}}: dışa dönüktür. (s. 13, 15)"}},
        {"ad": "easy-going", "renk": "#c58b5a", "svg": k2_svg["easy-going"],
         "aciklama": "Uysal, rahat demektir. Kolay kolay kızmaz, herkesle iyi geçinir.",
         "ek": "Kitaptaki ankette {{easy-going}} için: {{relaxed and friendly}} (rahat ve arkadaş canlısı). (s. 26)",
         "akilda": "uysal, rahat",
         "ornek": "He's always kind and easy-going.",
         "ornekTr": "O her zaman nazik ve uysaldır. (s. 14)",
         "soru": {"soru": "{{easy-going}} biri nasıldır?",
                  "secenekler": ["Çok kızgın", "Rahat ve arkadaş canlısı", "Hep geç kalan"], "dogru": 1,
                  "ipucu": "Resimdeki kişi hamakta gözleri kapalı dinleniyor.",
                  "aciklama": "Kitapta {{easy-going}} kişiler {{relaxed and friendly}} diye anlatılıyor. (s. 26)"}},
        {"ad": "stubborn", "renk": "#ff7a33", "svg": k2_svg["stubborn"],
         "aciklama": "İnatçı demektir. Bildiğinden kolay kolay vazgeçmez.",
         "ek": "Kitapta bu özellik olumsuz sayılır: {{There is one negative thing about her.}} Onun olumsuz bir yanı var. (s. 10, 25)",
         "akilda": "inatçı",
         "ornek": "Laura is a little stubborn.",
         "ornekTr": "Laura biraz inatçıdır. (s. 14)",
         "soru": {"soru": "{{Laura is a little stubborn.}} Bu cümle ne anlatıyor?",
                  "secenekler": ["Laura biraz inatçı.", "Laura çok cömert.", "Laura hep dakik."], "dogru": 0,
                  "ipucu": "Resimdeki yüz kollarını kavuşturmuş, kaşları çatık.",
                  "aciklama": "{{stubborn}} inatçı, {{a little}} biraz demektir. (s. 14)"}},
        {"ad": "selfish", "renk": "#ff5a6e", "svg": k2_svg["selfish"],
         "aciklama": "Bencil demektir. Kitaptaki tanım: yalnızca kendini düşünen, başkalarını düşünmeyen kişi.",
         "ek": "Kitaptaki İngilizce tanım: {{Caring only about yourself, not others.}} (s. 10)",
         "akilda": "bencil",
         "ornek": "I like her because she isn't selfish.",
         "ornekTr": "Onu seviyorum çünkü bencil değil. (s. 23)",
         "soru": {"soru": "{{selfish}} kişi ne yapar?",
                  "secenekler": ["Herkese yardım eder.", "Sadece kendini düşünür.", "Her yere zamanında gider."], "dogru": 1,
                  "ipucu": "Resimdeki kişi bütün kutuları kendine almış.",
                  "aciklama": "{{selfish}}: yalnızca kendini düşünen, bencil kişi. (s. 10)"}},
    ],
    "gruplar": [{"soru": "Bu özellik olumlu mu, olumsuz mu?",
                 "kutular": [{"etiket": "Olumlu özellik", "uyeler": ["honest", "generous", "punctual", "outgoing", "easy-going"]},
                             {"etiket": "Olumsuz özellik", "uyeler": ["stubborn", "selfish"]}]}],
    "biliyorMusun": [
        "Kitaptaki bir ankette 100 gence arkadaşlıkta en önemli özellik soruluyor. Neredeyse yarısı (%49) {{honest}} diyor. (s. 26)",
        "Kitaptaki ödev örneğinde Einstein şöyle anlatılıyor: {{Einstein was very intelligent and curious.}} Çok zeki ve meraklıydı. (s. 18)",
    ],
    "akildaKalsin": [
        "Kişiliği sormak için: {{What is she like?}} (O nasıl biri?)",
        "{{honest}} dürüst, {{generous}} cömert, {{punctual}} dakik.",
        "{{outgoing}} dışa dönük, {{easy-going}} uysal ve rahat.",
        "Olumsuz özellikler: {{stubborn}} inatçı, {{selfish}} bencil.",
        "{{always}} her zaman, {{never}} asla: {{He is always honest and polite.}}",
    ],
    "merakKutusu": [
        {"soru": "{{What is she like?}} ile {{What does she look like?}} aynı soru mu?",
         "cevap": "Hayır. {{What does she look like?}} dış görünüşü sorar: güzel, uzun boylu gibi. {{What is she like?}} kişiliği sorar: dakik, dürüst gibi. Kitapta ikisi art arda soruluyor. (s. 17)"},
        {"soru": "Dakik biri geç kalır mı?",
         "cevap": "Kalmaz. Kitapta Frank kendini dakik diye anlatıyor ve şöyle diyor: {{I don't like being late.}} Geç kalmayı sevmem. (s. 22)"},
        {"soru": "Kitapta başka hangi kişilik kelimeleri var?",
         "cevap": "{{smart}} akıllı, {{kind}} nazik, {{helpful}} yardımsever, {{patient}} sabırlı, {{fair}} adil, {{polite}} kibar, {{hardworking}} çalışkan, {{supportive}} destekleyici. (s. 12, 14, 16, 25)"},
        {"soru": "Bir kişinin hem iyi hem kötü özelliği olabilir mi?",
         "cevap": "Evet. Kitapta Jack, arkadaşı Henry için {{He can sometimes be really stubborn, but I don't care much about it.}} diyor: Bazen çok inatçı olabiliyor ama pek umursamıyorum. (s. 23)"},
        {"soru": "{{neither of them are selfish}} ne demek?",
         "cevap": "İkisi de bencil değil demektir. Kitapta Jim ve Mike için söyleniyor; ikisi de paylaşmayı sever. (s. 13)"},
    ],
    "dusunVeYaz": [
        {"soru": "En iyi arkadaşının kişiliğini İngilizce bir iki cümleyle anlat. {{My best friend is}} ile başla.",
         "ornekCevap": "My best friend is Merve. She's always honest, generous and fair.",
         "anahtarlar": ["my best friend", "is", "always"]}],
    "sorular": [
        {"soru": "Dinle. Hangi kelimeyi duydun?", "secenekler": ["selfish", "honest", "stubborn"], "dogru": 1,
         "ipucu": "Dürüst anlamındaki kelimeyi duydun. İstersen yavaş dinle.",
         "aciklama": "Duyduğun kelime {{honest}}: dürüst. (s. 12)", "dinle": "honest"},
        {"soru": "Dinle. Hangi kelimeyi duydun?", "secenekler": ["outgoing", "generous", "punctual"], "dogru": 2,
         "ipucu": "Saatle, zamanla ilgili kelimeyi duydun.",
         "aciklama": "Duyduğun kelime {{punctual}}: dakik. (s. 17)", "dinle": "punctual"},
        {"soru": "Birinin kişiliğini sormak için hangi soru kullanılır?",
         "secenekler": ["What is she like?", "What does she look like?", "How old is she?"], "dogru": 0,
         "ipucu": "Konunun başındaki soruyu hatırla: içinde {{look}} yoktu.",
         "aciklama": "{{What is she like?}} O nasıl biri? demektir; kişiliği sorar. (s. 17)"},
        {"soru": "Hangi kelime olumsuz bir özelliği anlatır?",
         "secenekler": ["generous", "easy-going", "stubborn"], "dogru": 2,
         "ipucu": "Gruplama oyununu hatırla: iki olumsuz özellik vardı.",
         "aciklama": "{{stubborn}} (inatçı) olumsuz bir özelliktir. (s. 10, 25)"},
        {"soru": "{{Caring only about yourself, not others.}} Bu tanım hangi kelimenin?",
         "secenekler": ["selfish", "honest", "outgoing"], "dogru": 0,
         "ipucu": "Yalnızca kendini düşünmek... Kutuları kendine alan kişiyi hatırla.",
         "aciklama": "Bu, kitapta {{selfish}} (bencil) kelimesinin tanımı. (s. 10)"},
        {"soru": "{{Willing to give and share.}} Bu tanım hangi kelimenin?",
         "secenekler": ["punctual", "generous", "stubborn"], "dogru": 1,
         "ipucu": "Vermek ve paylaşmak: hediye kutusu resmini hatırla.",
         "aciklama": "Bu, kitapta {{generous}} (cömert) kelimesinin tanımı. (s. 10)"},
        {"soru": "Kitaptaki metne göre Mehmet nasıl biri? {{He's always kind and easy-going.}}",
         "secenekler": ["Nazik ve uysal", "İnatçı ve bencil", "Dakik ve sosyal"], "dogru": 0,
         "ipucu": "{{kind}} nazik demekti; {{easy-going}} kartını hatırla.",
         "aciklama": "{{kind}} nazik, {{easy-going}} uysal demektir. (s. 14)"},
        {"soru": "Dinle. Hangi kelimeyi duydun?", "secenekler": ["honest", "easy-going", "outgoing"], "dogru": 2,
         "ipucu": "Arkadaşlarıyla takılmayı seven kişiyi anlatan kelime.",
         "aciklama": "Duyduğun kelime {{outgoing}}: dışa dönük. (s. 13)", "dinle": "outgoing"},
        {"soru": "{{Mark is a generous boy. He is always honest and polite.}} Hangisi Mark için doğru?",
         "secenekler": ["Mark bencil.", "Mark cömert ve dürüst.", "Mark inatçı."], "dogru": 1,
         "ipucu": "Cümlede {{generous}} ve {{honest}} kelimeleri var.",
         "aciklama": "Mark cömert, dürüst ve kibar biri. (s. 14)"},
        {"soru": "Kitaptaki ankette arkadaşlıkta en önemli özellik hangisi seçilmiş?",
         "secenekler": ["funny", "generous", "honest"], "dogru": 2,
         "ipucu": "Neredeyse yarısı (%49) bu özelliği seçmişti. Biliyor musun? kutusuna bak.",
         "aciklama": "Gençlerin %49'u {{honest}} demiş. (s. 26)"},
    ],
    "kelimeler": [
        {"en": "smart", "tr": "akıllı", "ornek": "She is very smart.", "ornekTr": "O çok akıllıdır. (s. 14)"},
        {"en": "kind", "tr": "nazik, iyi kalpli", "ornek": "He's always kind and easy-going.", "ornekTr": "O her zaman nazik ve uysaldır. (s. 14)"},
        {"en": "helpful", "tr": "yardımsever"},
        {"en": "patient", "tr": "sabırlı"},
        {"en": "fair", "tr": "adil"},
        {"en": "polite", "tr": "kibar", "ornek": "He is always honest and polite.", "ornekTr": "O her zaman dürüst ve kibardır. (s. 14)"},
        {"en": "hardworking", "tr": "çalışkan"},
        {"en": "funny", "tr": "komik, eğlenceli"},
        {"en": "tolerant", "tr": "hoşgörülü"},
        {"en": "supportive", "tr": "destekleyici", "ornek": "She's supportive, smart and understanding.", "ornekTr": "O destekleyici, akıllı ve anlayışlıdır. (s. 25)"},
        {"en": "understanding", "tr": "anlayışlı"},
        {"en": "intelligent", "tr": "zeki"},
        {"en": "curious", "tr": "meraklı"},
        {"en": "creative", "tr": "yaratıcı"},
    ],
    "cumleler": [
        {"en": "Mark is a generous boy.", "tr": "Mark cömert bir çocuktur. (s. 14)"},
        {"en": "He is always honest and polite.", "tr": "O her zaman dürüst ve kibardır. (s. 14)"},
        {"en": "Laura is a little stubborn.", "tr": "Laura biraz inatçıdır. (s. 14)"},
        {"en": "He likes helping people.", "tr": "İnsanlara yardım etmeyi sever. (s. 14)"},
        {"en": "She goes everywhere on time.", "tr": "Her yere zamanında gider. (s. 15)"},
        {"en": "She is punctual, honest and smart.", "tr": "O dakik, dürüst ve akıllıdır. (s. 17)"},
    ],
    "okuma": {
        "baslik": "Selma, Mehmet, Mark and Laura", "sayfa": "s. 14",
        "cumleler": [
            {"en": "This is Selma.", "tr": "Bu Selma."},
            {"en": "She likes staying in her room and reading books.", "tr": "Odasında kalıp kitap okumayı sever."},
            {"en": "She isn't very outgoing, but she is very punctual.", "tr": "Çok dışa dönük değildir ama çok dakiktir."},
            {"en": "She is tall.", "tr": "Uzun boyludur."},
            {"en": "Her eyes are big and brown.", "tr": "Gözleri büyük ve kahverengidir."},
            {"en": "She looks beautiful with her headscarf.", "tr": "Başörtüsüyle güzel görünür."},
            {"en": "Mehmet is a nice man.", "tr": "Mehmet iyi bir adamdır."},
            {"en": "He's always kind and easy-going.", "tr": "Her zaman nazik ve uysaldır."},
            {"en": "He likes helping people.", "tr": "İnsanlara yardım etmeyi sever."},
            {"en": "Mehmet is tall and slim.", "tr": "Mehmet uzun boylu ve incedir."},
            {"en": "He has short black hair and brown eyes.", "tr": "Kısa siyah saçları ve kahverengi gözleri var."},
            {"en": "His name is Mark.", "tr": "Onun adı Mark."},
            {"en": "He is young and handsome.", "tr": "Genç ve yakışıklıdır."},
            {"en": "He has blue eyes and brown hair.", "tr": "Mavi gözleri ve kahverengi saçları var."},
            {"en": "Mark is a generous boy.", "tr": "Mark cömert bir çocuktur."},
            {"en": "He is always honest and polite.", "tr": "Her zaman dürüst ve kibardır."},
            {"en": "Laura is very cute with green eyes and long straight hair.", "tr": "Laura yeşil gözlü, uzun düz saçlı, çok sevimli biridir."},
            {"en": "Her hair is brown.", "tr": "Saçı kahverengidir."},
            {"en": "She has a nice smile.", "tr": "Güzel bir gülüşü var."},
            {"en": "Laura is a little stubborn.", "tr": "Laura biraz inatçıdır."},
            {"en": "She is very smart.", "tr": "Çok akıllıdır."},
        ],
        "sorular": [
            {"soru": "Kim çok dakik?", "secenekler": ["Laura", "Selma", "Mark"], "dogru": 1,
             "ipucu": "{{She isn't very outgoing, but she is very punctual.}} cümlesi kimi anlatıyor?",
             "aciklama": "Selma çok dışa dönük değil ama çok dakik. (s. 14)"},
            {"soru": "İnsanlara yardım etmeyi kim sever?", "secenekler": ["Mehmet", "Laura", "Selma"], "dogru": 0,
             "ipucu": "{{He likes helping people.}} cümlesi kimden sonra geliyor?",
             "aciklama": "Mehmet nazik, uysal ve yardımsever biri. (s. 14)"},
            {"soru": "Laura'nın olumsuz özelliği hangisi?", "secenekler": ["Bencil", "Geç kalan", "Biraz inatçı"], "dogru": 2,
             "ipucu": "{{Laura is a little ...}} cümlesini hatırla.",
             "aciklama": "{{Laura is a little stubborn.}} Laura biraz inatçı. (s. 14)"},
        ],
    },
}

# ---------------------------------------------------------------- u1k3 Karşılaştırma
k3_svg = {
    "taller than": svg(
        ZEMIN, kisi(40, 104, 58, "#3cc47c", 11), kisi(78, 104, 30, "#ff7a33", 10),
        "<path d='M100 100V30M94 38l6-8 6 8' stroke='#f2c14e' stroke-width='4' fill='none' stroke-linecap='round' stroke-linejoin='round'/>"),
    "younger than": svg(
        ZEMIN, kisi(36, 104, 40, "#5a6280", 12),
        "<path d='M24 50q12-16 24 0' fill='#c9ccd6'/><path d='M50 70l10 4v30' stroke='#c58b5a' stroke-width='4' stroke-linecap='round' fill='none'/>",
        kisi(84, 104, 24, "#ff5a8a", 10),
        "<path d='M74 62q10-10 20 0' fill='#7a4a2a'/><path d='M100 30l3 6 6 3-6 3-3 6-3-6-6-3 6-3z' fill='#f2c14e'/>"),
    "slimmer than": svg(
        ZEMIN, kisi(36, 104, 46, "#4ea8de", 11, "gul", 14), kisi(80, 104, 40, "#ff7a33", 12, "gul", 34),
        "<path d='M20 72h8M44 72h8M24 68l-4 4 4 4M48 68l4 4-4 4' stroke='#f2c14e' stroke-width='3' fill='none' stroke-linecap='round'/>"),
    "heavier than": svg(
        "<path d='M60 42v50' stroke='#5a6280' stroke-width='5'/><path d='M44 104h32l-16-12z' fill='#5a6280'/>",
        "<path d='M18 50l84-16' stroke='#c9ccd6' stroke-width='5' stroke-linecap='round'/><circle cx='60' cy='42' r='5' fill='#f2c14e'/>",
        "<rect x='14' y='22' width='26' height='26' rx='4' fill='#ff7a33'/><rect x='84' y='22' width='16' height='14' rx='3' fill='#4ea8de'/>",
        "<path d='M27 60v20M21 74l6 6 6-6' stroke='#f2c14e' stroke-width='4' fill='none' stroke-linecap='round' stroke-linejoin='round'/>"),
    "more outgoing than": svg(
        ZEMIN, kisi(26, 104, 26, "#5a6280", 9, "duz"),
        kisi(76, 104, 34, "#3cc47c", 10), kisi(100, 104, 24, "#4ea8de", 8), kisi(56, 104, 24, "#ff5a8a", 8),
        "<path d='M84 70l10-18' stroke='#ffd6a5' stroke-width='5' stroke-linecap='round'/>",
        "<path d='M60 22h40q6 0 6 6v8q0 6-6 6H78l-6 6v-6H60q-6 0-6-6v-8q0-6 6-6z' fill='#f5f6fa'/>",
        "<circle cx='70' cy='32' r='3' fill='#ff5a6e'/><circle cx='80' cy='32' r='3' fill='#f2c14e'/><circle cx='90' cy='32' r='3' fill='#3cc47c'/>"),
    "better than": svg(
        ZEMIN,
        "<rect x='16' y='70' width='26' height='34' rx='3' fill='#c9ccd6'/><rect x='47' y='50' width='26' height='54' rx='3' fill='#f2c14e'/><rect x='78' y='82' width='26' height='22' rx='3' fill='#c58b5a'/>",
        yuz(60, 34, 12),
        "<path d='M54 18l3 4 3-6 3 6 3-4v6H54z' fill='#f2c14e'/>",
        "<circle cx='29' cy='60' r='8' fill='#ffd6a5'/><circle cx='91' cy='72' r='8' fill='#ffd6a5'/>"),
}

KURAL = "(Kural kitap dışı: British Council LearnEnglish Teens.)"

u1k3 = {
    "id": "u1k3",
    "unite": "Unit 1: Appearance and Personality",
    "baslik": "Karşılaştırma (taller than, more … than)",
    "sayfalar": "s. 11–26",
    "giris": "Bu konuda iki kişiyi karşılaştırmayı öğreneceğiz: kim daha uzun, kim daha genç, kim daha dışa dönük? İngilizcede karşılaştırırken {{than}} kelimesini kullanırız. Örnek: {{He's more outgoing than Jim.}} O, Jim'den daha dışa dönük.",
    "kavramlar": [
        {"ad": "taller than", "renk": "#3cc47c", "svg": k3_svg["taller than"],
         "aciklama": "-den daha uzun (boylu) demektir. Kısa sıfatın sonuna {{-er}} eklenir, arkasından {{than}} gelir.",
         "ek": "{{tall}} → {{taller}}. Kitapta: {{young}} → {{younger}}, {{old}} → {{older}}. " + KURAL,
         "akilda": "-den daha uzun",
         "ornek": "Jim is taller than Mike.",
         "ornekTr": "Jim, Mike'tan daha uzun boylu. (s. 13)",
         "soru": {"soru": "{{Jim is taller than Mike.}} Hangisi doğru?",
                  "secenekler": ["Mike daha uzun boylu.", "Jim daha uzun boylu.", "İkisi aynı boyda."], "dogru": 1,
                  "ipucu": "{{than}} kelimesinden önce gelen kişi daha uzun olandır.",
                  "aciklama": "{{Jim is taller than Mike.}} Jim, Mike'tan daha uzun. (s. 13)"}},
        {"ad": "younger than", "renk": "#ff5a8a", "svg": k3_svg["younger than"],
         "aciklama": "-den daha genç (küçük) demektir. {{young}} kelimesine {{-er}} eklenir.",
         "ek": "Zıttı {{older than}}: -den daha yaşlı, daha büyük. Kitapta: {{She is older than Tom and me.}} (s. 16)",
         "akilda": "-den daha genç",
         "ornek": "Nina is younger than Dave.",
         "ornekTr": "Nina, Dave'den daha genç. (s. 26)",
         "soru": {"soru": "Nina 15, Dave 18 yaşında. Hangi cümle doğru?",
                  "secenekler": ["Dave is younger than Nina.", "Nina is older than Dave.", "Nina is younger than Dave."], "dogru": 2,
                  "ipucu": "Yaşı küçük olan kim? {{younger}} daha genç demekti.",
                  "aciklama": "15 yaşındaki Nina daha genç: {{Nina is younger than Dave.}} (s. 26)"}},
        {"ad": "slimmer than", "renk": "#4ea8de", "svg": k3_svg["slimmer than"],
         "aciklama": "-den daha ince demektir. {{slim}} kelimesinde son harf ikilenir: {{slimmer}}.",
         "ek": "Kısa kelime bir ünlü + bir ünsüzle bitiyorsa son harf ikilenir: {{big}} → {{bigger}}. " + KURAL,
         "akilda": "-den daha ince",
         "ornek": "He's taller and slimmer than me.",
         "ornekTr": "O, benden daha uzun ve daha ince. (s. 23)",
         "soru": {"soru": "{{slim}} kelimesine {{-er}} eklenince nasıl yazılır?",
                  "secenekler": ["slimer", "slimmer", "more slim"], "dogru": 1,
                  "ipucu": "Kartta son harf için ne yazıyordu? İkilenir.",
                  "aciklama": "Son harf ikilenir: {{slim}} → {{slimmer}}. (s. 23)"}},
        {"ad": "heavier than", "renk": "#ff7a33", "svg": k3_svg["heavier than"],
         "aciklama": "-den daha ağır (kilolu) demektir. {{heavy}} kelimesindeki {{y}}, {{i}} olur: {{heavier}}.",
         "ek": "Kitapta bir örnek daha: {{funny}} → {{funnier}} (daha komik). (s. 24) " + KURAL,
         "akilda": "-den daha ağır",
         "ornek": "Dave is heavier than Nina.",
         "ornekTr": "Dave, Nina'dan daha ağır. (s. 26)",
         "soru": {"soru": "{{heavy}} kelimesinin karşılaştırma hâli hangisi?",
                  "secenekler": ["heavyer", "more heavy", "heavier"], "dogru": 2,
                  "ipucu": "Terazide ağır kutuyu hatırla: {{y}} harfi neye dönüşüyordu?",
                  "aciklama": "{{y}} → {{i}} olur ve {{-er}} eklenir: {{heavier}}. (s. 26)"}},
        {"ad": "more outgoing than", "renk": "#f2c14e", "svg": k3_svg["more outgoing than"],
         "aciklama": "-den daha dışa dönük demektir. Uzun sıfatlara {{-er}} eklenmez; önüne {{more}} gelir.",
         "ek": "Kitapta: {{more hardworking}}, {{more easy-going}}, {{more punctual}}, {{more stubborn}}. " + KURAL,
         "akilda": "-den daha dışa dönük",
         "ornek": "He's more outgoing than Jim.",
         "ornekTr": "O, Jim'den daha dışa dönük. (s. 13)",
         "soru": {"soru": "Hangi cümle doğru?",
                  "secenekler": ["He's more outgoing than Jim.", "He's outgoinger than Jim.", "He's more outgoinger than Jim."], "dogru": 0,
                  "ipucu": "Uzun kelimeye {{-er}} eklenmiyordu; önüne ne geliyordu?",
                  "aciklama": "Uzun sıfat: {{more outgoing than}}. (s. 13)"}},
        {"ad": "better than", "renk": "#c58b5a", "svg": k3_svg["better than"],
         "aciklama": "-den daha iyi demektir. {{good}} düzensizdir: {{gooder}} denmez, {{better}} denir.",
         "ek": "Zıttı {{worse than}}: -den daha kötü ({{bad}} → {{worse}}). Kitaptaki dinlemede: {{better / worse than everyone else}}. (s. 11) " + KURAL,
         "akilda": "-den daha iyi",
         "soru": {"soru": "{{good}} kelimesinin karşılaştırma hâli hangisi?",
                  "secenekler": ["gooder", "better", "more good"], "dogru": 1,
                  "ipucu": "Bu kelime düzensizdi; kartın başlığına bak.",
                  "aciklama": "{{good}} → {{better}}, {{bad}} → {{worse}}. (s. 11)"}},
    ],
    "gruplar": [{"soru": "Bu karşılaştırma nasıl yapılmış?",
                 "kutular": [{"etiket": "Sadece -er eklenmiş", "uyeler": ["taller than", "younger than"]},
                             {"etiket": "-er eklenirken yazılış değişmiş", "uyeler": ["slimmer than", "heavier than"]},
                             {"etiket": "-er yok: more ya da düzensiz", "uyeler": ["more outgoing than", "better than"]}]}],
    "biliyorMusun": [
        "{{more}} tek başına da kullanılır: {{I like Henry more than my other friends.}} Henry'yi diğer arkadaşlarımdan daha çok seviyorum. (s. 23)",
        "Kitaptaki testte Dave 182 cm, Nina 162 cm. Bu yüzden {{Nina is taller than Dave.}} cümlesi yanlıştır. (s. 26)",
    ],
    "akildaKalsin": [
        "{{than}} = -den, -dan (daha).",
        "Kısa sıfat + {{-er}} + {{than}}: {{taller than}}, {{younger than}}.",
        "Yazılışa dikkat: {{slim}} → {{slimmer}}, {{heavy}} → {{heavier}}.",
        "Uzun sıfatlarda {{more}}: {{more outgoing than}}.",
        "Düzensizler: {{good}} → {{better}}, {{bad}} → {{worse}}.",
    ],
    "merakKutusu": [
        {"soru": "Neden bazen {{-er}}, bazen {{more}} kullanılıyor?",
         "cevap": "Kısa kelimelere {{-er}} eklenir: {{taller}}, {{younger}}. Uzun kelimelerin önüne {{more}} gelir: {{more outgoing}}, {{more hardworking}}. Örnekler kitapta, kural kitap dışı (British Council LearnEnglish Teens). (s. 13, 16)"},
        {"soru": "{{slimmer}} kelimesinde neden iki {{m}} var?",
         "cevap": "Kısa bir kelime bir ünlü + bir ünsüzle bitiyorsa, {{-er}} eklenirken son harf ikilenir: {{slim}} → {{slimmer}}. Kural kitap dışı (British Council LearnEnglish Teens); örnek kitapta. (s. 23)"},
        {"soru": "{{than}} cümlede nereye gelir?",
         "cevap": "Karşılaştırma kelimesinden hemen sonra, karşılaştırılan kişiden önce: {{Nina is younger than Dave.}} (s. 26)"},
        {"soru": "İki özelliği aynı anda karşılaştırabilir miyim?",
         "cevap": "Evet, {{and}} ile bağlarsın: {{He's taller and slimmer than me.}} O, benden daha uzun ve daha ince. (s. 23)"},
        {"soru": "{{than me}} mi denir, {{than I}} mı?",
         "cevap": "Kitaptaki örneklerde {{than me}} kullanılıyor: {{He is more hardworking than me.}} O, benden daha çalışkan. (s. 16)"},
    ],
    "dusunVeYaz": [
        {"soru": "Kendini bir aile üyenle ya da arkadaşınla karşılaştır. Bir cümlede {{-er than}}, bir cümlede {{more ... than}} kullan.",
         "ornekCevap": "I am taller than my sister. My sister is more outgoing than me.",
         "anahtarlar": ["er than", "more", "than"]}],
    "sorular": [
        {"soru": "Dinle. Hangi kelimeyi duydun?", "secenekler": ["older", "younger", "taller"], "dogru": 1,
         "ipucu": "Yaşla ilgili, daha genç anlamındaki kelime. Yavaş dinle düğmesini dene.",
         "aciklama": "Duyduğun kelime {{younger}}: daha genç. (s. 26)", "dinle": "younger"},
        {"soru": "Dinle. Hangisini duydun?", "secenekler": ["more outgoing", "more punctual", "more stubborn"], "dogru": 0,
         "ipucu": "Arkadaşlarıyla takılmayı seven kişiyi anlatan kelime.",
         "aciklama": "Duyduğun {{more outgoing}}: daha dışa dönük. (s. 13)", "dinle": "more outgoing"},
        {"soru": "{{than}} kelimesinin anlamı hangisi?",
         "secenekler": ["ve", "ama", "-den, -dan (daha)"], "dogru": 2,
         "ipucu": "{{Jim is taller than Mike.}} Jim, Mike'TAN daha uzun.",
         "aciklama": "{{than}}, Türkçedeki -den, -dan ekine karşılık gelir. (s. 13)"},
        {"soru": "{{Anne is ___ punctual than Jane.}} Boşluğa ne gelir?",
         "secenekler": ["more", "better", "-er"], "dogru": 0,
         "ipucu": "{{punctual}} uzun bir kelime. Uzun kelimelerin önüne ne geliyordu?",
         "aciklama": "{{Anne is more punctual than Jane.}} (s. 21)"},
        {"soru": "{{tall}} kelimesinin karşılaştırma hâli hangisi?",
         "secenekler": ["more tall", "taller", "tallier"], "dogru": 1,
         "ipucu": "Kısa kelime: sadece {{-er}} eklenir.",
         "aciklama": "{{tall}} → {{taller}}. (s. 13)"},
        {"soru": "Dave 182 cm, Nina 162 cm. Hangi cümle doğru?",
         "secenekler": ["Nina is taller than Dave.", "Dave is taller than Nina.", "Dave is shorter than Nina."], "dogru": 1,
         "ipucu": "Boyu uzun olan kim? {{than}}'dan önce o gelmeli.",
         "aciklama": "182 cm, 162 cm'den uzundur: Dave daha uzun. (s. 26)"},
        {"soru": "{{bad}} kelimesinin karşılaştırma hâli hangisi?",
         "secenekler": ["badder", "more bad", "worse"], "dogru": 2,
         "ipucu": "{{good}} gibi düzensiz bir kelime. {{better}} kartında zıttı yazıyordu.",
         "aciklama": "{{bad}} → {{worse}}, daha kötü. (s. 11)"},
        {"soru": "Jack, Henry için {{He's taller and slimmer than me.}} diyor. Kim daha kısa?",
         "secenekler": ["Jack", "Henry", "İkisi aynı"], "dogru": 0,
         "ipucu": "{{me}} burada konuşan kişi: Jack.",
         "aciklama": "Henry daha uzun, yani Jack daha kısa: {{Jack is shorter than Henry.}} (s. 23)"},
        {"soru": "{{funny}} kelimesinin karşılaştırma hâli hangisi?",
         "secenekler": ["funnier", "funnyer", "more funny"], "dogru": 0,
         "ipucu": "{{heavy}} → {{heavier}} gibi: {{y}} harfi {{i}} olur.",
         "aciklama": "{{funny}} → {{funnier}}. Kitapta: {{is funnier than you}}. (s. 24)"},
        {"soru": "Rosie: {{Tom is my brother. He is younger than me.}} Hangisi doğru?",
         "secenekler": ["Tom, Rosie'den büyük.", "Tom, Rosie'den küçük.", "Tom ve Rosie aynı yaşta."], "dogru": 1,
         "ipucu": "{{younger}} daha genç, yani daha küçük demekti.",
         "aciklama": "{{He is younger than me.}} Tom, Rosie'den daha küçük. (s. 16)"},
    ],
    "kelimeler": [
        {"en": "than", "tr": "-den, -dan (daha)"},
        {"en": "older", "tr": "daha yaşlı, daha büyük", "ornek": "She is older than Tom and me.", "ornekTr": "O, Tom'dan ve benden büyük. (s. 16)"},
        {"en": "shorter", "tr": "daha kısa", "ornek": "Jack is shorter than Henry.", "ornekTr": "Jack, Henry'den daha kısa. (s. 23)"},
        {"en": "funnier", "tr": "daha komik"},
        {"en": "worse", "tr": "daha kötü"},
        {"en": "more hardworking", "tr": "daha çalışkan", "ornek": "He is more hardworking than me.", "ornekTr": "O, benden daha çalışkan. (s. 16)"},
        {"en": "more easy-going", "tr": "daha uysal"},
        {"en": "more stubborn", "tr": "daha inatçı", "ornek": "Mike's more stubborn, but neither of them are selfish.", "ornekTr": "Mike daha inatçı, ama ikisi de bencil değil. (s. 13)"},
        {"en": "more punctual", "tr": "daha dakik", "ornek": "Anne is more punctual than Jane.", "ornekTr": "Anne, Jane'den daha dakik. (s. 21)"},
        {"en": "more than", "tr": "-den daha çok", "ornek": "I like Henry more than my other friends.", "ornekTr": "Henry'yi diğer arkadaşlarımdan daha çok seviyorum. (s. 23)"},
    ],
    "cumleler": [
        {"en": "Jim is taller than Mike.", "tr": "Jim, Mike'tan daha uzun boylu. (s. 13)"},
        {"en": "He's more outgoing than Jim.", "tr": "O, Jim'den daha dışa dönük. (s. 13)"},
        {"en": "He is more hardworking than me.", "tr": "O, benden daha çalışkan. (s. 16)"},
        {"en": "Anne is more punctual than Jane.", "tr": "Anne, Jane'den daha dakik. (s. 21)"},
        {"en": "He's taller and slimmer than me.", "tr": "O, benden daha uzun ve daha ince. (s. 23)"},
        {"en": "Nina is younger than Dave.", "tr": "Nina, Dave'den daha genç. (s. 26)"},
        {"en": "Dave is heavier than Nina.", "tr": "Dave, Nina'dan daha ağır. (s. 26)"},
    ],
    "okuma": {
        "baslik": "Rosie's Family", "sayfa": "s. 16",
        "cumleler": [
            {"en": "Hello. I'm Rosie.", "tr": "Merhaba. Ben Rosie."},
            {"en": "This is my family.", "tr": "Bu benim ailem."},
            {"en": "My father Frank is a handsome man.", "tr": "Babam Frank yakışıklı bir adam."},
            {"en": "He has nice brown eyes, and his hair is black.", "tr": "Güzel kahverengi gözleri var, saçı siyah."},
            {"en": "My mother Helen is beautiful with blue eyes and long straight blonde hair.", "tr": "Annem Helen mavi gözlü, uzun düz sarı saçlı, güzel bir kadın."},
            {"en": "Tom is my brother.", "tr": "Tom benim erkek kardeşim."},
            {"en": "He is younger than me, but he is taller.", "tr": "Benden küçük ama daha uzun boylu."},
            {"en": "He is a smart boy.", "tr": "Akıllı bir çocuk."},
            {"en": "He is more hardworking than me.", "tr": "Benden daha çalışkan."},
            {"en": "And Sheila, she is my sister.", "tr": "Ve Sheila, o benim kız kardeşim."},
            {"en": "She is older than Tom and me.", "tr": "Tom'dan ve benden büyük."},
            {"en": "She is a cute girl.", "tr": "Sevimli bir kız."},
            {"en": "She is more easy-going than me because I am stubborn.", "tr": "Benden daha uysal, çünkü ben inatçıyım."},
            {"en": "I love my family a lot.", "tr": "Ailemi çok seviyorum."},
        ],
        "sorular": [
            {"soru": "Tom, Rosie'ye göre nasıl?", "secenekler": ["Daha büyük ve daha kısa", "Daha küçük ama daha uzun", "Aynı yaşta"], "dogru": 1,
             "ipucu": "{{He is younger than me, but he is taller.}} cümlesine bak.",
             "aciklama": "Tom, Rosie'den küçük ama daha uzun boylu. (s. 16)"},
            {"soru": "Ailenin en büyük çocuğu kim?", "secenekler": ["Sheila", "Tom", "Rosie"], "dogru": 0,
             "ipucu": "{{She is older than Tom and me.}} cümlesi kimi anlatıyor?",
             "aciklama": "Sheila, Tom'dan ve Rosie'den büyük. (s. 16)"},
            {"soru": "Sheila neden Rosie'den daha uysal?", "secenekler": ["Çünkü Sheila daha uzun.", "Çünkü Tom daha çalışkan.", "Çünkü Rosie inatçı."], "dogru": 2,
             "ipucu": "{{because I am stubborn}} kısmını hatırla.",
             "aciklama": "{{She is more easy-going than me because I am stubborn.}} (s. 16)"},
        ],
    },
}

for d in (u1k2, u1k3):
    with open(f"public/ing1/konular/{d['id']}.json", "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print("yazıldı:", d["id"])
